### ISSUE TITLE
Library is not thread safe

### ISSUE THREAD

**Issue by theborakompanioni** [audit4j/audit4j-core#19]
Since you are looping over all handlers and set the AuditEvent for the each of them.. it is possible to lose events - the library is therefore not thread safe.
See `AuditEventProcessor` L70 https://github.com/audit4j/audit4j-core/blob/master/src/main/java/org/audit4j/core/AuditEventProcessor.java#L70

**Comment by janithb** [comment]
Audit4j framework based on reactor pattern to process events asynchronously. Hence all the processing based on single event loop which runs on a single thread but still serve the high performance processing. I don't see any issue  ass long as handling exceptions properly. What do you think?

**Comment by theborakompanioni** [comment]
Ahh! Ok, that's nice. I have just looked at the processor level. Thank you.
