### ISSUE TITLE
Is it possible to set the scheme where audit table will be created?

### ISSUE THREAD

**Issue by msamichev** [audit4j/audit4j-core#20]
Hello,

I have huge need to have opportunity to set the scheme where audit table will be created.

Can you add this property to DB handler?

Thanks

**Comment by janithb** [comment]
Do you want a custom name for audit tables?

**Comment by msamichev** [comment]
No, I would like have opportunity to set only schema name for table. For example if I use postgresql then your plugin creates table in public schema and full name of audit table looks like "public.audit". And I need to have opportunity to change schema name to look like this "custom_schema.audit".

Thanks

**Comment by janithb** [comment]
You can specify the schema parameter in the connection url. 

jdbc:postgresql://localhost:5432/mydatabase?currentSchema=custom_schema

Please refer below links.

http://stackoverflow.com/questions/4168689/is-it-possible-to-specify-schema-when-connecting-to-postgres-with-jdbc

https://jdbc.postgresql.org/documentation/94/connect.html#connection-parameters

**Comment by msamichev** [comment]
Yep, as a workaround It can be done, but in our app, we have several schemas simultaneously and we use ORM (in persistence layer) and we wouldn't like to set exact schema name in connection url. We would like to have more flexible solution to set schema name (and as optional  - to set table name).

Can you add additional parameter in DbHandler definition?

Thanks.

**Comment by janithb** [comment]
Yes. This is possible. We will add this to next release, however we have to test it before release a major release. Appreciate if you can add this feature as a contribution. The [source code](https://github.com/audit4j/audit4j-db) is pretty simple. We do accept pull requests.

**Comment by janithb** [comment]
Fixed in 2.5.0
