### ISSUE TITLE
http://audit4j.org/ does not work

### ISSUE THREAD

**Issue by fjcano-stratio** [audit4j/audit4j-core#44]
Hello,

I'm trying to get documentation about audit4j and it is "down". Did you move to other site?

Thanks,

**Comment by janithb** [comment]
Thanks for informing. We are working for this issue with our hosting provider. We'll let you know one the site is available. In the meantime please feel free to ask any questing in out google group.

https://groups.google.com/forum/#!forum/audit4j

Regards,
Janith

**Comment by janithb** [comment]
audit4j.org is available now.

**Comment by fjcano-stratio** [comment]
Thanks a lot
