### ISSUE TITLE
audit4j-core SimpleLayout

### ISSUE THREAD

**Issue by sdcavanaugh** [audit4j/audit4j-core#46]
Using audit4j.conf.yaml for configuration.  When I configure a SimpleLayout with a dateFormat like this

> layout: !org.audit4j.core.layout.SimpleLayout {
> dateFormat: "yyyy-MM-dd HH:mm:ss"
> }

I get a this exception:

> Caused by: com.esotericsoftware.yamlbeans.YamlReader$YamlReaderException: Line 7, column 13: > Unable to find property 'dateFormat' on class: org.audit4j.core.layout.SimpleLayout

Adding _public String getDateFormat()_ method to SimpleLayout seems to correct this.

**Comment by franck-benault** [comment]
The version 2.5.0 of audit4j-core solves this issue

**Comment by janithb** [comment]
Fixed

**Comment by franck-benault** [comment]
This issue has been solved in the code, but is not yet integrated in a version
please look at this issue
https://github.com/audit4j/audit4j-core/issues/71

I will ask to create a new version of audit4j-core
