### ISSUE TITLE
Can't load Audit4J configuration file from desired path

### ISSUE THREAD

**Issue by italopaiva** [audit4j/audit4j-core#47]
In the configuration section of Audit4J documentation it says that the first step that Audit4J try to do is:

"1. Check whether configurations that are directly injected are available in the Context. If available; proceed with the injected configuration. If not, jump to step 7."

**How do I "directly inject the configurations in the Context" ?**

I'm not able to choose a configuration file from a folder in my application (like 'src/main/resources', for instance), Audit4J is always jumping to the step 7 and creating a new configuration file.

Thanks!

***OBS.:*** I don't know if it is a bug, but when Audit4J creates the configuration file, its name is being "auit4J.conf.yml" instead of "audit4J.conf.yml".

**Comment by sdcavanaugh** [comment]
What version are you using?  2.4.1 saves the configuration to
audit4j.conf.yaml.

**Comment by italopaiva** [comment]
@sdcavanaugh, I'm using the version 2.2.0.

Thanks for the quick answer!

**Comment by italopaiva** [comment]
I upgraded the to 2.4.1 version and now is working fine!

Thanks, @sdcavanaugh!
